### ISSUE TITLE
Get this working for Linuxbrew

### ISSUE THREAD

**Issue by nathaneastwood** [nathaneastwood/brew-ds#2]
[Twitter request](https://twitter.com/sjackman/status/852177982261047301) to get this working for [Linux](https://github.com/Linuxbrew/brew)

**Comment by sjackman** [comment]
I'm a developer of Linuxbrew. If you also use Linux and would be interested in getting this running on Linux, I'd be happy to help. There are some differences between Homebrew and Linuxbrew, which for example doesn't have Homebrew/cask.

**Comment by nathaneastwood** [comment]
That would be useful. I've just had a brief review of the Linuxbrew documentation so will see how I get on :)

**Comment by nathaneastwood** [comment]
@garethclews let's look at this tomorrow?

**Comment by ghost** [comment]
@nathaneastwood yep, the cask issue is the only problem - I guess we can find out the distro and try to fall back on the package manager for that kinda thing. I'll have a think about it anyway. 

I guess I'll have to work on build.sh as well then, it was just a quick and dirty version for our use. If its going to be used wider then I'll make it safer.

**Comment by ghost** [comment]
Just submitted a PR but be warned its not tested on linux yet.

**Comment by nathaneastwood** [comment]
Merged PR #5

**Comment by sjackman** [comment]
You can if you like install R and Texlive using Linuxbrew, which works on all distributions of Linux. R is available on macOS as well (but not Texlive).
```sh
brew install homebrew/science/r texlive
```

**Comment by ghost** [comment]
@sjackman so homebrew/science/r is in the `base_brew` list - I tried to separate out the CLI to the GUI version and have the GUI one in the package manager bits, I tried check to see whether that was the correct R package for each package manager so that it had the GUI [the equivalent to the R.app from cask] but I'm sure I failed and you could end up with multiple installations going on.

TeX makes it far more awkward in that the best version for MacOS to me is the mactex distro, if you fancied making a PR and editing the script so that there was a `nix_brew` that added texlive in to the brew call on that side then that would be welcome. Even just looking at that one it was awkward because all the distros have the schemes labelled differently.


This is where the differences between MacOS bundling in .app and linux spreading things far and wide comes in. I also don't like enforcing e.g. AUR usage on people - I can see why you don't have cask. One thing I actually didn't look at was whether flatpak solved this issue and am too busy right now to test a huge variety of VMs.

**Comment by sjackman** [comment]
What does AUR mean?

For the R GUI, I'd recommend installing [RStudio](https://www.rstudio.com/products/rstudio/download/) over `R.app` or the equivalent GUI for Linux.

**Comment by ghost** [comment]
We do install RStudio, @nathaneastwood puts the default GUI in as well because some people prefer it [and he has to use it for teaching purposes]. 

AUR is the [Arch User Repository](https://aur.archlinux.org/) and has analogues in other distros: portage overlays, PPAs etc. It is a user contributed package repo.
